package:
    name: "ucsc-bedclip"
    version: "377"
source:
    url: "http://hgdownload.cse.ucsc.edu/admin/exe/userApps.archive/userApps.v377.src.tgz"                # [linux]
    fn: "userApps.src.tgz"                                                                     # [linux]
    md5: "30ce911f0935307c810d3b795b985b63"                                                    # [linux]
    patches:
      - patch1.patch

build:                                                                                       # [osx]
    number: 1

requirements:
    build:
        - {{ compiler('c') }} 8
        - make
        - libpng 1.6                                             # [linux]
        - mysql 5.7                                                 # [linux]
    host:
        - zlib                                                      # [linux]
        - openssl 1.1                                             # [linux]
        - libuuid 2.32
    run:                                                            # [linux]
        - libpng 1.6                                             # [linux]
        - mysql 5.7                                                 # [linux]
        - zlib                                                      # [linux]
        - openssl 1.1                                             # [linux]
about:
    home: "http://hgdownload.cse.ucsc.edu/admin/exe/"
    license: "varies; see http://genome.ucsc.edu/license"
    summary: "Remove lines from bed file that refer to off-chromosome places."





