{% set version = "2.54.0" %}
{% set name = "biomaRt" %}
{% set bioc = "3.14" %}

package:
  name: 'bioconductor-biomart'
  version: '2.50.0'
source:
  url:
    - 'https://bioconductor.org/packages/release/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
  md5: 72f4afffedb7c70fda011572e8a1687d
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: BiocStyle, knitr, rmarkdown, testthat, mockery
requirements:
  host:
    - 'bioconductor-annotationdbi >=1.56.0,<1.57.0'
    - 'bioconductor-biocfilecache >=2.2.0,<2.3.0'
    - 'r-base >=4.1,<4.2'
    - r-digest
    - r-httr
    - r-progress
    - r-rappdirs
    - r-stringr
    - r-xml
    - r-xml2
  run:
    - 'bioconductor-annotationdbi >=1.56.0,<1.57.0'
    - 'bioconductor-biocfilecache >=2.2.0,<2.3.0'
    - 'r-base >=4.1,<4.2'
    - r-digest
    - r-httr
    - r-progress
    - r-rappdirs
    - r-stringr
    - r-xml
    - r-xml2
test:
  commands:
    - '$R -e "library(''biomaRt'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/biomaRt.html'
  license: Artistic-2.0
  summary: 'Interface to BioMart databases (i.e. Ensembl)'
  description: 'In recent years a wealth of biological data has become available in public data repositories. Easy access to these valuable data resources and firm integration with data analysis is needed for comprehensive bioinformatics data analysis. biomaRt provides an interface to a growing collection of databases implementing the BioMart software suite (<http://www.biomart.org>). The package enables retrieval of large amounts of data in a uniform way without the need to know the underlying database schemas or write complex SQL queries. The most prominent examples of BioMart databases are maintain by Ensembl, which provides biomaRt users direct access to a diverse set of data and enables a wide range of powerful online queries from gene annotation to database mining.'
extra:
  identifiers:
    - biotools:biomaRt
    - doi:10.1038/nprot.2009.97
  parent_recipe:
    name: bioconductor-biomart
    path: recipes/bioconductor-biomart
    version: 2.36.1

