{% set version = "3.2.2" %}
{% set name = "AnnotationHub" %}
{% set bioc = "3.14" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/3.14/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
  md5: 1504583a31b71617e95c9c1793ed90d6
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: IRanges, GenomicRanges, GenomeInfoDb, VariantAnnotation, Rsamtools, rtracklayer, BiocStyle, knitr, AnnotationForge, rBiopaxParser, RUnit, GenomicFeatures, MSnbase, mzR, Biostrings, SummarizedExperiment, ExperimentHub, gdsfmt, rmarkdown, HubPub
requirements:
  host:
    - 'bioconductor-annotationdbi >=1.56.0,<1.57.0'
    - 'bioconductor-biocfilecache >=2.2.0,<2.3.0'
    - 'bioconductor-biocgenerics >=0.40.0,<0.41.0'
    - 'bioconductor-biocversion >=3.14.0,<3.15.0'
    - 'bioconductor-interactivedisplaybase >=1.32.0,<1.33.0'
    - 'bioconductor-s4vectors >=0.32.0,<0.33.0'
    - 'r-base >=4.1,<4.2'
    - r-biocmanager
    - r-curl
    - r-dplyr
    - r-httr
    - r-rappdirs
    - r-rsqlite
    - r-yaml
  run:
    - 'bioconductor-annotationdbi >=1.56.0,<1.57.0'
    - 'bioconductor-biocfilecache >=2.2.0,<2.3.0'
    - 'bioconductor-biocgenerics >=0.40.0,<0.41.0'
    - 'bioconductor-biocversion >=3.14.0,<3.15.0'
    - 'bioconductor-interactivedisplaybase >=1.32.0,<1.33.0'
    - 'bioconductor-s4vectors >=0.32.0,<0.33.0'
    - 'r-base >=4.1,<4.2'
    - r-biocmanager
    - r-curl
    - r-dplyr
    - r-httr
    - r-rappdirs
    - r-rsqlite
    - r-yaml
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Client to access AnnotationHub resources'
  description: 'This package provides a client for the Bioconductor AnnotationHub web resource. The AnnotationHub web resource provides a central location where genomic files (e.g., VCF, bed, wig) and other resources from standard locations (e.g., UCSC, Ensembl) can be discovered. The resource includes metadata about each resource, e.g., a textual description, tags, and date of modification. The client creates and manages a local cache of files retrieved by the user, helping with quick and reproducible access.'
extra:
  identifiers:
    - biotools:annotationhub
    - doi:10.1038/nmeth.3252
  parent_recipe:
    name: bioconductor-annotationhub
    path: recipes/bioconductor-annotationhub
    version: 2.12.1

