# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /home/builder/r-4.2.0/aggregateR/r-filelock-feedstock/recipe, last modified Wed Jun  1 21:42:24 2022
# ------------------------------------------------

package:
  name: r-filelock
  version: 1.0.2
source:
  sha256: ac2915950789b16c43a625a2b8dab6ba423588db4a7d0daa75b74518b82b1403
  url:
    - https://cran.r-project.org/src/contrib/Archive/filelock/filelock_1.0.2.tar.gz
    - https://cran.r-project.org/src/contrib/filelock_1.0.2.tar.gz
build:
  number: '0'
  rpaths:
    - lib/
    - lib/R/lib/
requirements:
  host:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - 'r-base >=4.1,<4.2'
test:
  commands:
    - $R -e "library('filelock')"
about:
  home: https://github.com/r-lib/filelock#readme
  license: MIT
  license_family: MIT
  license_file:
    - /home/builder/r-4.2.0/miniconda/envs/r-4.2.0/conda-bld/r-filelock_1654180119399/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/R/share/licenses/MIT
    - LICENSE
  summary: Place an exclusive or shared lock on a file. It uses 'LockFile' on Windows
    and 'fcntl' locks on Unix-like systems.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - katietz




