# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Sep 16 16:57:13 2022
# ------------------------------------------------

package:
  name: libpng
  version: 1.6.38
source:
  patches:
    - 0001-Include-pkg-config-files-in-the-Windows-packages-too.patch
    - 0002-Ensure-that-lm-is-not-included-in-Windows-pkg-config.patch
    - libpng-arm-free.patch
  sha256: e2b5e1b4329650992c041996cf1269681b341191dc07ffed816c555769cceb77
  url: http://download.sourceforge.net/libpng/libpng-1.6.38.tar.gz
build:
  number: '0'
  run_exports:
    - libpng >=1.6.38,<1.7.0a0
  string: hf9034f9_0
requirements:
  build:
    - _openmp_mutex 4.5 2_gnu
    - autoconf 2.69 pl5321h689fa9f_11
    - automake 1.16.5 pl5321h8af1aa0_0
    - binutils_impl_linux-aarch64 2.36.1 h026399b_2
    - binutils_linux-aarch64 2.36 h7854541_10
    - gcc_impl_linux-aarch64 10.4.0 hbc23e19_16
    - gcc_linux-aarch64 10.4.0 h72ad2ee_10
    - kernel-headers_linux-aarch64 4.18.0 h5b4a56d_13
    - ld_impl_linux-aarch64 2.36.1 h02ad14f_2
    - libgcc-devel_linux-aarch64 10.4.0 hf691355_16
    - libgcc-ng 12.1.0 h3242a24_16
    - libgomp 12.1.0 h3242a24_16
    - libnsl 2.0.0 hf897c2e_0
    - libsanitizer 10.4.0 h69a60c7_16
    - libstdcxx-ng 12.1.0 hd01590b_16
    - libtool 2.4.6 h01db608_1008
    - m4 1.4.18 h516909a_1001
    - make 4.3 h309ac5b_1
    - perl 5.32.1 2_hf897c2e_perl5
    - sysroot_linux-aarch64 2.17 h43d7e78_13
  host:
    - _openmp_mutex 4.5 2_gnu
    - libgcc-ng 12.1.0 h3242a24_16
    - libgomp 12.1.0 h3242a24_16
    - libzlib 1.2.12 h4e544f5_3
    - zlib 1.2.12 h4e544f5_3
  run:
    - libgcc-ng >=12
    - libzlib >=1.2.12,<1.3.0a0
test:
  commands:
    - test -f ${PREFIX}/lib/libpng.a
    - test -f ${PREFIX}/lib/libpng${SHLIB_EXT}
    - libpng-config --version
about:
  description: 'libpng is the official PNG reference library. It supports almost all
    PNG

    features, is extensible, and has been extensively tested for over 20 years.

    '
  dev_url: https://sourceforge.net/p/libpng/code/ci/libpng16/tree/
  doc_url: http://www.libpng.org/pub/png/libpng.html
  home: http://www.libpng.org/pub/png/libpng.html
  license: zlib-acknowledgement
  license_file: LICENSE
  license_url: http://www.libpng.org/pub/png/src/libpng-LICENSE.txt
  summary: PNG reference library
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - msarahan
    - ocefpaf
    - pkgw
